# Generated by Django 5.2.4 on 2025-09-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_time', 'id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='stylist',
            options={'ordering': ['first_name', 'last_name', 'id']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
