# Generated by Django 5.2.4 on 2025-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('RAZORPAY', 'Razorpay')], default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
