# Generated by Django 5.2.4 on 2026-09-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_visitorlead'),
        ('salon', '0004_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='salon.appointment')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='salon.stylist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_commissions', to='api.tenant')),
            ],
        ),
    ]
