# Generated by Django 5.2.4 on 2026-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_stylistcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Share of each completed service paid to this stylist', max_digits=5),
        ),
    ]
