# Generated by Django 5.2.4 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_stylist_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the customer pays: price, plus GST when the price excludes it', max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage. 0 means no tax is calculated', max_digits=5),
        ),
        migrations.AddField(
            model_name='service',
            name='price_includes_tax',
            field=models.BooleanField(default=True, help_text='The listed price already contains GST'),
        ),
    ]
