# Generated by Django 5.2.4 on 2025-07-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='api.class'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='storage_used_mb',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='ClassFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='api.class')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
    ]
