# Generated by Django 5.2.4 on 2025-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_appointment_doctor_remove_appointment_patient_and_more'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='education.class'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassFeeStructure',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='QualityControl',
        ),
        migrations.DeleteModel(
            name='ReportCard',
        ),
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
