# Generated by Django 5.2.4 on 2025-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='storage_used_mb',
            field=models.FloatField(default=0),
        ),
    ]
