# Generated by Django 5.2.4 on 2025-07-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(default='#2196F3', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_audit_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_custom_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_daily_backups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_future_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_new_features_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_phone_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_sla_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_strategy_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_white_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='savings_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
