# Generated by Django 5.2.4 on 2025-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plan_billing_cycle_plan_color_plan_has_api_access_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
