# Generated by Django 5.2.4 on 2025-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invoice_invoiceitem_invoicepayment_invoicetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_pharmacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_retail',
            field=models.BooleanField(default=False),
        ),
    ]
