# Generated by Django 5.2.4 on 2025-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_plan_has_pharmacy_plan_has_retail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_salon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('pharmacy', 'Pharmacy'), ('retail', 'Retail'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('salon', 'Salon')], max_length=50),
        ),
    ]
