# Generated by Django 5.2.4 on 2025-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_plan_has_hotel_plan_has_restaurant_plan_has_salon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_salon',
            field=models.BooleanField(default=False),
        ),
    ]
