# Generated by Django 5.2.4 on 2025-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tenant_has_hotel_tenant_has_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_admissions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='public_api_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='public_booking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='public_orders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
