# Generated by Django 5.2.4 on 2025-09-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tenant_public_admissions_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
    ]
