# Generated by Django 5.2.4 on 2025-10-31 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PERMISSION_DENIED', 'Permission Denied'), ('FILE_UPLOAD', 'File Upload'), ('FILE_DOWNLOAD', 'File Download'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('VIEW', 'View'), ('OTHER', 'Other')], max_length=50)),
                ('resource_type', models.CharField(help_text='Type of resource (e.g., Student, Payment, User)', max_length=100)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the affected resource', null=True)),
                ('resource_name', models.CharField(blank=True, help_text='Name/identifier of the resource', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_data', models.JSONField(blank=True, help_text='Sanitized request data', null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='api_auditlo_user_id_c3bd49_idx'), models.Index(fields=['resource_type', 'resource_id'], name='api_auditlo_resourc_c074b3_idx'), models.Index(fields=['ip_address'], name='api_auditlo_ip_addr_5903d9_idx'), models.Index(fields=['created_at'], name='api_auditlo_created_ec4a64_idx'), models.Index(fields=['action', 'created_at'], name='api_auditlo_action_e69819_idx')],
            },
        ),
    ]
