# Generated by Django 5.2.4 on 2025-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo for reports, bills, and documents', null=True, upload_to='tenant_logos/'),
        ),
    ]
