# Generated by Django 5.2.4 on 2025-11-02 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(choices=[('education', 'Education'), ('pharmacy', 'Pharmacy'), ('retail', 'Retail'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('salon', 'Salon'), ('general', 'General'), ('system', 'System')], default='general', max_length=50)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reminder', 'Reminder'), ('announcement', 'Announcement'), ('alert', 'Alert')], max_length=20)),
                ('title_template', models.CharField(help_text='Template for notification title, use {variables}', max_length=200)),
                ('message_template', models.TextField(help_text='Template for notification message, use {variables}')),
                ('variables', models.JSONField(default=list, help_text="List of available variables, e.g., ['student_name', 'class_name', 'amount']")),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('default_expiry_days', models.IntegerField(blank=True, help_text='Auto-expire after N days', null=True)),
                ('email_subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('email_body_template', models.TextField(blank=True, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=160, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reminder', 'Reminder'), ('announcement', 'Announcement'), ('alert', 'Alert')], default='info', max_length=20)),
                ('module', models.CharField(choices=[('education', 'Education'), ('pharmacy', 'Pharmacy'), ('retail', 'Retail'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('salon', 'Salon'), ('general', 'General'), ('system', 'System')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('action_url', models.URLField(blank=True, help_text='Link to related page/resource', null=True)),
                ('action_label', models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, help_text="e.g., 'Student', 'Sale', 'Booking'", max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the referenced object', null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide after this date', null=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name or emoji', max_length=50, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notifications', to='api.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='api.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Send notifications via email')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Send notifications via SMS')),
                ('push_enabled', models.BooleanField(default=True, help_text='Show browser push notifications')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Show in-app notifications')),
                ('module_preferences', models.JSONField(default=dict, help_text="Per-module preferences, e.g., {'education': {'email': True, 'sms': False}}")),
                ('type_preferences', models.JSONField(default=dict, help_text="Per-type preferences, e.g., {'reminder': {'email': True}, 'alert': {'sms': True}}")),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send notifications after this time", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Resume notifications after this time', null=True)),
                ('max_emails_per_day', models.IntegerField(default=50, help_text='Maximum email notifications per day')),
                ('max_sms_per_day', models.IntegerField(default=10, help_text='Maximum SMS notifications per day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='api_notific_user_id_c3bb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'module', 'created_at'], name='api_notific_tenant__aaafdb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='api_notific_user_id_5b04a6_idx'),
        ),
    ]
