# Generated by Django 5.2.4 on 2025-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='grace_period_end_date',
            field=models.DateField(blank=True, help_text='End date of grace period after expiration', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='Date when current subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='Date when current subscription started', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('grace_period', 'Grace Period')], default='active', help_text='Current subscription status', max_length=20),
        ),
    ]
