# Generated by Django 5.2.4 on 2025-11-02 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('customization', 'Customization'), ('web_development', 'Web Development'), ('app_development', 'App Development'), ('both', 'Web + App Development')], help_text='Type of service requested', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Detailed description of requirements')),
                ('budget_range', models.CharField(blank=True, help_text="Budget range (e.g., '10k-50k', '50k-1L', '1L+')", max_length=50)),
                ('timeline', models.CharField(blank=True, help_text="Expected timeline (e.g., '1 month', '3 months', '6 months')", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Custom Service Request',
                'verbose_name_plural': 'Custom Service Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
