# Generated by Django 5.2.4 on 2025-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_support_ticket_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='api_support_tenant__c954e0_idx',
            old_name='api_support_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='api_support_priorit_3b0f06_idx',
            old_name='api_support_priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='api_support_assigne_faf6da_idx',
            old_name='api_support_assigne_idx',
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', help_text='Billing frequency: Monthly (Free), Annual (paid plans), or Custom (Enterprise)', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color',
            field=models.CharField(default='#2196F3', help_text='Hex color code for plan badge/UI (e.g., #2196F3=blue, #4CAF50=green, #FF9800=orange, #9C27B0=purple)', max_length=7),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(help_text="Short description shown on pricing page (e.g., 'Perfect for getting started', 'Ideal for growing businesses')"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_analytics',
            field=models.BooleanField(default=False, help_text='Advanced analytics and reporting: Charts, trends, forecasting, custom reports'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False, help_text='REST API access for integrations: Connect external systems, mobile apps, third-party tools'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_audit_logs',
            field=models.BooleanField(default=False, help_text='Audit Logging: Track all user actions, who did what, when, from where (for security/compliance)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_billing',
            field=models.BooleanField(default=False, help_text='Billing Management: Invoice generation, payment tracking, billing features'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_custom_reports',
            field=models.BooleanField(default=False, help_text='Custom Reports: Create custom report templates, layouts, schedules with custom fields'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_daily_backups',
            field=models.BooleanField(default=False, help_text='Daily Backups: Automated daily data backups, point-in-time recovery'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_dashboard',
            field=models.BooleanField(default=True, help_text='Main dashboard access - Shows overview, stats, quick actions (usually ON for all plans)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_education',
            field=models.BooleanField(default=False, help_text='Education ERP: Students, Classes, Fees, Attendance, Report Cards'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_future_discount',
            field=models.BooleanField(default=False, help_text='Future Discount: Discount on future upgrades/add-ons (typically 10-20% off)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_healthcare',
            field=models.BooleanField(default=False, help_text='Healthcare Management: Patients, Appointments, Medical records (Future feature)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_hotel',
            field=models.BooleanField(default=False, help_text='Hotel Management: Rooms, Bookings, Guests, Check-in/out'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_inventory',
            field=models.BooleanField(default=False, help_text='Base inventory management (usually enabled by industry modules)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_new_features_access',
            field=models.BooleanField(default=False, help_text='New Features Access: Early access to new features (beta), test before general release'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_onboarding',
            field=models.BooleanField(default=False, help_text='Onboarding Assistance: Dedicated setup help, training, migration support'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_pharmacy',
            field=models.BooleanField(default=False, help_text='Pharmacy Management: Medicines, Prescriptions, Sales, Inventory'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_phone_support',
            field=models.BooleanField(default=False, help_text='Phone Support: Direct phone number, call scheduling, voice support availability'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False, help_text='Priority Support: Faster response times, priority queue for support tickets'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_qc',
            field=models.BooleanField(default=False, help_text='Quality Control: QC workflows, approval processes, quality checks'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_restaurant',
            field=models.BooleanField(default=False, help_text='Restaurant Management: Menu, Tables, Orders, Kitchen display'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_retail',
            field=models.BooleanField(default=False, help_text='Retail/Wholesale: Products, Warehouses, Multi-location inventory, Sales'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_salon',
            field=models.BooleanField(default=False, help_text='Salon Management: Services, Appointments, Stylists, Customers'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_sla_support',
            field=models.BooleanField(default=False, help_text='SLA Support: Service Level Agreement guarantee, uptime commitment, response time guarantees'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_strategy_call',
            field=models.BooleanField(default=False, help_text='Strategy Call: 1-on-1 consultation call with expert, business analysis, optimization advice'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text='White Label: Remove Zenith ERP branding, allow custom logo, colors, branding'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(blank=True, help_text='Maximum number of users allowed. Leave BLANK for unlimited users. Examples: Free=2, Starter=25, Pro=100', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly equivalent price for annual plans. Example: ₹4,500/year = ₹375/month (for display purposes)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text="Plan display name (e.g., 'Free', 'Starter', 'Pro', 'Business'). This appears on pricing pages.", max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='popular',
            field=models.BooleanField(default=False, help_text="Mark as 'Most Popular' to highlight on homepage with badge and special styling"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Indian Rupees (₹). Set to 0 for Free plan. Leave blank for Custom/Enterprise pricing.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='savings_text',
            field=models.CharField(blank=True, help_text="Optional savings message (e.g., 'Save ₹2,989 annually') shown on pricing page", max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='storage_limit_mb',
            field=models.IntegerField(help_text='Storage limit in Megabytes. 1 GB = 1024 MB. Examples: 500 MB = 500, 5 GB = 5120, 20 GB = 20480, 50 GB = 51200'),
        ),
    ]
