# Generated by Django 5.2.4 on 2025-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_api_support_tenant__idx_api_support_tenant__c954e0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='percentage_calculation_method',
            field=models.CharField(choices=[('SIMPLE', 'Simple: (Total Marks / Max Marks) × 100'), ('SUBJECT_WISE', 'Subject-wise: Average of subject percentages'), ('WEIGHTED', 'Weighted: Based on subject weightage (if configured)')], default='SIMPLE', help_text='Method for calculating overall percentage in report cards', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='percentage_excluded_subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subject IDs to exclude from percentage calculation (JSON array)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='percentage_rounding',
            field=models.IntegerField(choices=[(0, '0 decimal places'), (1, '1 decimal place'), (2, '2 decimal places')], default=2, help_text='Number of decimal places for percentage display'),
        ),
    ]
