# Generated by Django 5.2.4 on 2025-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_percentage_calculation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='percentage_calculation_scope',
            field=models.CharField(choices=[('TERM_WISE', 'Term-wise: Calculate percentage for each term separately'), ('ALL_TERMS', 'All Terms: Calculate percentage across all terms combined')], default='TERM_WISE', help_text='Whether to calculate percentage per term or across all terms', max_length=20),
        ),
    ]
