# Generated by Django 5.2.4 on 2025-11-20 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_percentage_calculation_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='description',
            field=models.CharField(blank=True, help_text='Human-readable description', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID of the related record (fee_payment_id, order_id, appointment_id, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='sector',
            field=models.CharField(choices=[('plan', 'Plan Subscription'), ('education', 'Education Fee'), ('restaurant', 'Restaurant Order'), ('salon', 'Salon Appointment'), ('pharmacy', 'Pharmacy Sale'), ('retail', 'Retail Sale'), ('hotel', 'Hotel Booking'), ('general', 'General Payment')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_enabled',
            field=models.BooleanField(default=False, help_text='Enable Razorpay payments for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='Razorpay Key ID from dashboard', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, help_text='Razorpay Key Secret from dashboard', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_setup_completed',
            field=models.BooleanField(default=False, help_text='Razorpay setup wizard completed'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, help_text='Razorpay Webhook Secret for payment verification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who initiated payment (null for webhook payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'sector', 'status'], name='api_payment_tenant__59f14c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'reference_id'], name='api_payment_tenant__9a034a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_id'], name='api_payment_payment_1573a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('payment_id',), name='unique_payment_id'),
        ),
    ]
