# Generated by Django 5.2.4 on 2025-11-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_contactlist_emailcampaign_emailactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='api.tenant')),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(help_text='Priority level (1=Lowest, 5=Highest)')),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('response_time_hours', models.IntegerField(help_text='Expected first response time in hours')),
                ('resolution_time_hours', models.IntegerField(help_text='Expected resolution time in hours')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_priorities', to='api.tenant')),
            ],
            options={
                'verbose_name_plural': 'Ticket Priorities',
                'ordering': ['-level'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
