# Generated by Django 5.2.4 on 2025-12-06 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tenant_upi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_token', models.CharField(help_text='Cookie/UUID tied to this visitor', max_length=64, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('landing_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('referrer', models.URLField(blank=True, max_length=1024, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=128, null=True)),
                ('form_submitted', models.BooleanField(default=False, help_text='True once the visitor sends any form data')),
                ('submitted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitted_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visitor Lead',
                'verbose_name_plural': 'Visitor Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
