# Generated by Django 5.2.4 on 2025-12-06 13:32

import django.utils.timezone
from django.db import migrations, models, connection
from django.db.migrations.operations.models import SeparateDatabaseAndState


def create_visitorlead_if_not_exists(apps, schema_editor):
    """
    Create VisitorLead model only if it doesn't already exist.
    This handles the case where 0033_visitorlead was already applied.
    """
    db_table = 'api_visitorlead'
    
    # Check if table already exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        table_exists = cursor.fetchone()[0]
    
    if not table_exists:
        # Table doesn't exist, create it
        VisitorLead = apps.get_model('api', 'VisitorLead')
        schema_editor.create_model(VisitorLead)
    # If table exists, do nothing (it was created by 0033_visitorlead)


def reverse_create_visitorlead(apps, schema_editor):
    """
    Reverse operation - only delete if this migration created it.
    Since 0033_visitorlead might have created it, we check first.
    """
    db_table = 'api_visitorlead'
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        table_exists = cursor.fetchone()[0]
    
    if table_exists:
        # Only delete if we're sure this migration created it
        # In practice, we'll be conservative and not delete
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tenant_upi_fields'),
        # Note: 0033_visitorlead may have already created the VisitorLead table
        # This migration checks and only creates if it doesn't exist
    ]

    operations = [
        # Use SeparateDatabaseAndState to update Django's state without creating the table
        # The table may already exist from 0033_visitorlead
        SeparateDatabaseAndState(
            # Update Django's state (for migration tracking)
            state_operations=[
                migrations.CreateModel(
                    name='VisitorLead',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('visitor_token', models.CharField(help_text='Cookie/UUID tied to this visitor', max_length=64, unique=True)),
                        ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                        ('user_agent', models.TextField(blank=True, null=True)),
                        ('landing_url', models.URLField(blank=True, max_length=1024, null=True)),
                        ('referrer', models.URLField(blank=True, max_length=1024, null=True)),
                        ('utm_source', models.CharField(blank=True, max_length=128, null=True)),
                        ('utm_medium', models.CharField(blank=True, max_length=128, null=True)),
                        ('utm_campaign', models.CharField(blank=True, max_length=128, null=True)),
                        ('utm_term', models.CharField(blank=True, max_length=128, null=True)),
                        ('utm_content', models.CharField(blank=True, max_length=128, null=True)),
                        ('form_submitted', models.BooleanField(default=False, help_text='True once the visitor sends any form data')),
                        ('submitted_name', models.CharField(blank=True, max_length=255, null=True)),
                        ('submitted_email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('submitted_phone', models.CharField(blank=True, max_length=30, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                    ],
                    options={
                        'verbose_name': 'Visitor Lead',
                        'verbose_name_plural': 'Visitor Leads',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            # Conditionally create the table only if it doesn't exist
            database_operations=[
                migrations.RunPython(
                    create_visitorlead_if_not_exists,
                    reverse_create_visitorlead,
                ),
            ],
        ),
    ]
