# Generated by Django 5.2.4 on 2026-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_visitorlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_razorpay_gateway',
            field=models.BooleanField(default=False, help_text='Whether this plan includes Razorpay gateway out of the box.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_addon_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price to unlock Razorpay if not included in plan. Editable from Django Admin.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_razorpay_unlocked',
            field=models.BooleanField(default=False, help_text='True if tenant purchased the Razorpay addon'),
        ),
    ]
