# Generated by Django 5.2.4 on 2026-09-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_plan_has_razorpay_gateway_plan_razorpay_addon_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_domain', models.CharField(blank=True, help_text='e.g., mail.theirsalon.com', max_length=255, null=True)),
                ('is_custom_email_enabled', models.BooleanField(default=False)),
                ('is_sms_enabled', models.BooleanField(default=False)),
                ('sms_used_this_month', models.IntegerField(default=0)),
                ('sms_monthly_limit', models.IntegerField(default=500)),
                ('is_whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_access_token', models.CharField(blank=True, help_text='OAuth token from Meta', max_length=500, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100, null=True)),
                ('whatsapp_used_this_month', models.IntegerField(default=0)),
                ('whatsapp_monthly_limit', models.IntegerField(default=500)),
                ('is_ai_enabled', models.BooleanField(default=False)),
                ('ai_tokens_used_this_month', models.IntegerField(default=0)),
                ('ai_tokens_monthly_limit', models.IntegerField(default=100000)),
                ('is_telegram_enabled', models.BooleanField(default=False)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='api.tenant')),
            ],
        ),
    ]
