# Generated by Django 5.2.4 on 2026-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_communicationthread_communicationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantfeatureconfig',
            name='ai_tokens_monthly_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenantfeatureconfig',
            name='sms_monthly_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenantfeatureconfig',
            name='whatsapp_monthly_limit',
            field=models.IntegerField(default=0),
        ),
    ]
