# Generated by Django 5.2.4 on 2026-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_tenantfeatureconfig_ai_tokens_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='twilio_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
