# Generated by Django 5.2.4 on 2026-09-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_tenantfeatureconfig_twilio_account_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='aws_access_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='aws_region',
            field=models.CharField(blank=True, default='ap-south-1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='aws_secret_access_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
