# Generated by Django 5.2.4 on 2026-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_tenantfeatureconfig_aws_access_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='managed_email_address',
            field=models.CharField(blank=True, help_text='The dedicated support email (e.g., info@tenant-domain.com)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='managed_phone_number',
            field=models.CharField(blank=True, help_text='The dedicated Twilio/Meta number you purchased for this tenant', max_length=20, null=True),
        ),
    ]
