# Generated by Django 5.2.4 on 2026-09-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_tenantfeatureconfig_managed_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g., smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='App Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='smtp_port',
            field=models.IntegerField(blank=True, help_text='e.g., 587 or 465', null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
