# Generated by Django 5.2.4 on 2026-09-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_tenantfeatureconfig_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='BYOK OpenAI API key (sk-proj-...)', max_length=255, null=True),
        ),
    ]
