# Generated by Django 5.2.4 on 2026-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_openai_api_key_to_tenant_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude')], default='openai', help_text='Which AI provider to use for AI Auto-Responder replies', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='azure_openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='azure_openai_deployment_name',
            field=models.CharField(blank=True, help_text="Your deployed model's name, e.g., gpt-4o-mini", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='azure_openai_endpoint',
            field=models.CharField(blank=True, help_text='e.g., https://your-resource.openai.azure.com/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='claude_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='claude_model',
            field=models.CharField(blank=True, default='claude-3-5-sonnet-latest', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-1.5-flash', max_length=100, null=True),
        ),
    ]
