# Generated by Django 5.2.4 on 2026-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_user_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='attachment_type',
            field=models.CharField(blank=True, help_text='image, document, audio, or video', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='communicationmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
