# Generated by Django 5.2.4 on 2026-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_chatchannel_chatmessage_chatchannelmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatureconfig',
            name='team_chat_ai_tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='channel_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group'), ('ai', 'AI Assistant')], max_length=10),
        ),
    ]
