# Generated by Django 5.2.4 on 2026-09-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_tenantfeatureconfig_team_chat_ai_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_manufacturing',
            field=models.BooleanField(default=False, help_text='Manufacturing: Raw materials, BOM, Production Orders, Quality Control, wholesale sales'),
        ),
    ]
