# Generated by Django 5.2.4 on 2026-09-23 20:02

import api.models.lead_capture
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_plan_has_manufacturing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='distance_km',
            field=models.FloatField(blank=True, help_text="Distance from the tenant's service-area center", null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='within_service_area',
            field=models.BooleanField(blank=True, help_text='None = unknown or no service area set', null=True),
        ),
        migrations.CreateModel(
            name='LeadCaptureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=api.models.lead_capture._new_public_key, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('intro_message', models.CharField(blank=True, default='Tell us what you need and we will get back to you.', max_length=300)),
                ('success_message', models.CharField(blank=True, default='Thank you! We have received your enquiry and will contact you soon.', max_length=300)),
                ('center_query', models.CharField(blank=True, help_text='Pincode or address of the service-area center', max_length=200)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('service_radius_km', models.PositiveIntegerField(blank=True, help_text='Blank = serve anywhere', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_capture_config', to='api.tenant')),
            ],
        ),
    ]
