# Generated by Django 5.2.4 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_geocodecache_contact_distance_km_contact_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gstin',
            field=models.CharField(blank=True, help_text='Your GST number, used to decide CGST/SGST or IGST on invoices', max_length=15),
        ),
    ]
