# Generated by Django 5.2.4 on 2026-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_tenant_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Printed on invoices and receipts'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, help_text='Printed on invoices and receipts', max_length=20),
        ),
    ]
