# Generated by Django 5.2.4 on 2025-08-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_customer_tenant_alter_medicine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode for scanning', max_length=100, null=True),
        ),
    ]
