# Generated by Django 5.2.4 on 2025-11-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_api_support_tenant__idx_api_support_tenant__c954e0_idx_and_more'),
        ('pharmacy', '0004_add_sale_return_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_enrolled',
            field=models.BooleanField(default=True, help_text='Whether customer is enrolled in loyalty program'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Current available loyalty points'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_points_earned',
            field=models.IntegerField(default=0, help_text='Lifetime points earned'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_points_redeemed',
            field=models.IntegerField(default=0, help_text='Lifetime points redeemed'),
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_required', models.IntegerField(help_text='Points needed to redeem this reward')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage if applicable', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount if applicable', max_digits=10, null=True)),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREE_ITEM', 'Free Item'), ('CASHBACK', 'Cashback'), ('OTHER', 'Other')], default='DISCOUNT', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_loyalty_rewards', to='api.tenant')),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed'), ('EXPIRED', 'Points Expired'), ('ADJUSTED', 'Points Adjusted')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed')),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when earned points expire (if applicable)', null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='pharmacy.customer')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='pharmacy.loyaltyreward')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='pharmacy.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_loyalty_transactions', to='api.tenant')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
