# Generated by Django 5.2.4 on 2026-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=50)),
                ('substitutes', models.TextField(blank=True, help_text='Comma separated list of substitutes or generic alternatives')),
            ],
        ),
    ]
