# Generated by Django 5.2.4 on 2025-07-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_department'),
        ('education', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_departments', to='api.tenant'),
        ),
    ]
