# Generated by Django 5.2.4 on 2025-07-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_address_userprofile_bio_and_more'),
        ('education', '0003_alter_department_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
    ]
