# Generated by Django 5.2.4 on 2025-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_emailverification'),
        ('education', '0005_remove_fee_student_remove_fee_tenant_feediscount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date', 'tenant')},
        ),
    ]
