# Generated by Django 5.2.4 on 2025-09-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tenant_has_hotel_tenant_has_restaurant_and_more'),
        ('education', '0006_alter_staffattendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_staff_attendance', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_staff_attendance', to='api.tenant'),
        ),
    ]
