# Generated by Django 5.2.4 on 2025-10-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_student_upper_id_admissionapplication'),
    ]

    operations = [
    ]
