# Generated by Django 5.2.4 on 2025-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cast',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'Other Backward Class (OBC)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('Other', 'Other')], default='General', help_text="Student's caste category (required)", max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, help_text="Student's religion", max_length=100, null=True),
        ),
    ]
