# Generated by Django 5.2.4 on 2025-11-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_api_support_tenant__idx_api_support_tenant__c954e0_idx_and_more'),
        ('education', '0015_feeinstallment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='class',
            name='next_class',
            field=models.ForeignKey(blank=True, help_text='Next class for promotion (optional, if not set, will use order+1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='education.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.IntegerField(default=0, help_text='Class order/sequence (1 for 1st std, 2 for 2nd std, etc.). Used for automatic promotion.'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('tenant', 'name')},
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('PROMOTED', 'Promoted'), ('REPEAT', 'Repeat Same Class'), ('DEMOTED', 'Demoted')], default='PROMOTED', max_length=20)),
                ('promotion_date', models.DateField(help_text='Date of promotion')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='education.academicyear')),
                ('from_class', models.ForeignKey(blank=True, help_text='Previous class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='education.class')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_students', to='api.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='education.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
                ('to_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='education.academicyear')),
                ('to_class', models.ForeignKey(blank=True, help_text='New class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='education.class')),
            ],
            options={
                'ordering': ['-promotion_date', '-created_at'],
                'unique_together': {('tenant', 'student', 'from_academic_year', 'to_academic_year')},
            },
        ),
    ]
