# Generated by Django 5.2.4 on 2025-11-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_api_support_tenant__idx_api_support_tenant__c954e0_idx_and_more'),
        ('education', '0016_add_class_promotion_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_uid',
            field=models.CharField(blank=True, help_text="Student's Aadhaar UID (12 digits)", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_aadhaar',
            field=models.CharField(blank=True, help_text="Father's Aadhaar UID (12 digits)", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_aadhaar',
            field=models.CharField(blank=True, help_text="Mother's Aadhaar UID (12 digits)", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, help_text="Mother's full name", max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentpromotion',
            unique_together={('tenant', 'student', 'promotion_date', 'from_class')},
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_number', models.CharField(help_text='Unique TC number (auto-generated)', max_length=50, unique=True)),
                ('issue_date', models.DateField(help_text='Date of TC issue')),
                ('reason_for_leaving', models.CharField(blank=True, help_text='Reason for leaving school', max_length=200, null=True)),
                ('last_attended_date', models.DateField(blank=True, help_text='Last date student attended classes', null=True)),
                ('student_name', models.CharField(help_text='Student name at time of TC', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, help_text='Original admission date', null=True)),
                ('last_class_promoted', models.CharField(blank=True, help_text='Last class in which student was promoted', max_length=100, null=True)),
                ('dues_paid', models.BooleanField(default=True, help_text='Whether all dues are cleared')),
                ('dues_details', models.TextField(blank=True, help_text='Details of any pending dues')),
                ('transferring_to_school', models.CharField(blank=True, help_text='Name of school/college transferring to', max_length=200, null=True)),
                ('transferring_to_address', models.TextField(blank=True, help_text='Address of new school')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('conduct_remarks', models.CharField(blank=True, help_text='Conduct and character remarks', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='education.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Principal who approved TC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tcs', to='api.userprofile')),
                ('class_obj', models.ForeignKey(help_text='Class at time of TC issue', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='education.class')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Admin/Principal who issued TC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tcs', to='api.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='education.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'unique_together': {('tenant', 'tc_number')},
            },
        ),
    ]
