# Generated by Django 5.2.4 on 2025-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_add_student_fields_and_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weightage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Weightage percentage for weighted calculation (e.g., 30 for 30%). Default is 100% (equal weight)', max_digits=5),
        ),
    ]
