# Generated by Django 5.2.4 on 2025-11-05 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_percentage_calculation_scope'),
        ('education', '0018_add_subject_weightage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Period 1, Period 2, Morning Assembly', max_length=50)),
                ('order', models.IntegerField(help_text='Period order/sequence (1, 2, 3...)')),
                ('start_time', models.TimeField(help_text='Period start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='Period end time (e.g., 10:00)')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break/recess period?')),
                ('break_type', models.CharField(blank=True, choices=[('recess', 'Recess'), ('lunch', 'Lunch Break'), ('assembly', 'Assembly'), ('other', 'Other')], help_text='Break type (only if is_break=True)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'ordering': ['order', 'start_time'],
                'unique_together': {('tenant', 'order', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Room 101, Lab A, Assembly Hall', max_length=100)),
                ('room_number', models.CharField(blank=True, help_text='Room number', max_length=50)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('library', 'Library'), ('hall', 'Hall'), ('computer_lab', 'Computer Lab'), ('physics_lab', 'Physics Lab'), ('chemistry_lab', 'Chemistry Lab'), ('biology_lab', 'Biology Lab'), ('other', 'Other')], default='classroom', max_length=50)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum capacity', null=True)),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (e.g., Projector, AC, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_rooms', to='api.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='education.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='education.class')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='education.period')),
                ('room', models.ForeignKey(blank=True, help_text='Assigned room/classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='education.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='education.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Assigned teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='api.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'ordering': ['academic_year', 'class_obj', 'day', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='SubstituteTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when substitute is needed')),
                ('reason', models.CharField(blank=True, help_text='Reason for substitution', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_teacher', models.ForeignKey(help_text='Original teacher', on_delete=django.db.models.deletion.CASCADE, related_name='original_substitutes', to='api.userprofile')),
                ('substitute_teacher', models.ForeignKey(help_text='Substitute teacher', on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='api.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='education.timetable')),
            ],
            options={
                'ordering': ['-date', 'timetable'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name (e.g., Diwali, Christmas)', max_length=200)),
                ('date', models.DateField(help_text='Holiday date')),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional Holiday'), ('religious', 'Religious Holiday'), ('school', 'School Holiday'), ('exam', 'Examination Holiday'), ('other', 'Other')], default='school', max_length=50)),
                ('is_recurring', models.BooleanField(default=False, help_text='Recurring holiday (e.g., every year)')),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='education.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('tenant', 'academic_year', 'date', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['tenant', 'academic_year', 'class_obj', 'day'], name='education_t_tenant__f9f129_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'day', 'period'], name='education_t_teacher_b099d8_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['room', 'day', 'period'], name='education_t_room_id_af11cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('tenant', 'academic_year', 'class_obj', 'day', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='substituteteacher',
            unique_together={('timetable', 'date')},
        ),
    ]
