# Generated by Django 5.2.4 on 2025-11-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_percentage_calculation_scope'),
        ('education', '0019_add_timetable_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Field name (e.g., 'Total Marks', 'Attendance %')", max_length=100)),
                ('field_key', models.CharField(help_text="Internal field key (e.g., 'total_marks', 'attendance_percentage')", max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('aggregate', 'Aggregate (Sum/Avg/Max/Min)')], default='number', max_length=20)),
                ('data_source', models.CharField(help_text="Data source model (e.g., 'ReportCard', 'MarksEntry', 'Attendance')", max_length=100)),
                ('data_field', models.CharField(help_text="Model field name (e.g., 'total_marks', 'percentage')", max_length=100)),
                ('aggregate_type', models.CharField(blank=True, choices=[('sum', 'Sum'), ('avg', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('count', 'Count')], help_text='Aggregate function if applicable', max_length=10, null=True)),
                ('filter_conditions', models.JSONField(default=dict, help_text='Filter conditions for this field')),
                ('display_name', models.CharField(blank=True, help_text='Display name in report', max_length=100)),
                ('format_string', models.CharField(blank=True, help_text="Format string (e.g., '%.2f', '%d')", max_length=50)),
                ('sortable', models.BooleanField(default=True, help_text='Can be sorted in report')),
                ('groupable', models.BooleanField(default=False, help_text='Can be grouped in report')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_fields', to='api.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Report description')),
                ('report_type', models.CharField(choices=[('student_performance', 'Student Performance'), ('class_performance', 'Class Performance'), ('attendance', 'Attendance'), ('fee_collection', 'Fee Collection'), ('comparative', 'Comparative Analysis'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('template_config', models.JSONField(default=dict, help_text='Drag-and-drop field configuration')),
                ('available_filters', models.JSONField(default=list, help_text='Available filter options')),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameters for the report')),
                ('is_public', models.BooleanField(default=False, help_text='Can be used by all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to='api.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='api.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
