# Generated by Django 5.2.4 on 2025-11-05 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_percentage_calculation_scope'),
        ('education', '0020_reportfield_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Exam name (e.g., 'Mid-Term Exam 2025')", max_length=200)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid-Term Exam'), ('final', 'Final Exam'), ('preliminary', 'Preliminary Exam'), ('mock', 'Mock Exam'), ('internal', 'Internal Assessment'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical Exam'), ('other', 'Other')], default='mid_term', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Exam description')),
                ('start_date', models.DateField(help_text='Exam start date')),
                ('end_date', models.DateField(help_text='Exam end date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='education.term')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'unique_together': {('tenant', 'name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Exam date')),
                ('start_time', models.TimeField(help_text='Exam start time')),
                ('end_time', models.TimeField(help_text='Exam end time')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, help_text='Maximum marks', max_digits=10)),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions for students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='education.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='education.exam')),
                ('invigilator', models.ForeignKey(blank=True, help_text='Assigned invigilator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='api.userprofile')),
                ('room', models.ForeignKey(blank=True, help_text='Exam hall/room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='education.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='education.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='api.tenant')),
            ],
            options={
                'ordering': ['date', 'start_time', 'class_obj'],
            },
        ),
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text="Seat number (e.g., 'A1', 'B5', 'Row 3 Seat 12')", max_length=50)),
                ('row_number', models.IntegerField(blank=True, help_text='Row number', null=True)),
                ('column_number', models.IntegerField(blank=True, help_text='Column/Seat number in row', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_arrangements', to='education.examschedule')),
                ('room', models.ForeignKey(blank=True, help_text='Exam hall/room (if different from schedule)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seating_arrangements', to='education.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seating', to='education.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_arrangements', to='api.tenant')),
            ],
            options={
                'ordering': ['exam_schedule', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Unique hall ticket number', max_length=100, unique=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now, help_text='Date when hall ticket was issued')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('issued', 'Issued'), ('downloaded', 'Downloaded'), ('cancelled', 'Cancelled')], default='generated', max_length=20)),
                ('photo_verified', models.BooleanField(default=False, help_text='Student photo verified')),
                ('signature_verified', models.BooleanField(default=False, help_text='Student signature verified')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='When student downloaded the ticket', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='education.exam')),
                ('exam_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_tickets', to='education.examschedule')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_hall_tickets', to='api.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='education.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='api.tenant')),
                ('seating_arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_tickets', to='education.seatingarrangement')),
            ],
            options={
                'ordering': ['-generated_at', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['tenant', 'exam', 'date'], name='education_e_tenant__ff5bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['class_obj', 'date'], name='education_e_class_o_735aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['room', 'date', 'start_time'], name='education_e_room_id_eae1fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('tenant', 'exam', 'class_obj', 'subject', 'date')},
        ),
        migrations.AddIndex(
            model_name='seatingarrangement',
            index=models.Index(fields=['exam_schedule', 'seat_number'], name='education_s_exam_sc_5d3183_idx'),
        ),
        migrations.AddIndex(
            model_name='seatingarrangement',
            index=models.Index(fields=['student', 'exam_schedule'], name='education_s_student_875111_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatingarrangement',
            unique_together={('tenant', 'exam_schedule', 'student')},
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['tenant', 'exam', 'student'], name='education_h_tenant__db5be5_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['ticket_number'], name='education_h_ticket__a64d83_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['status'], name='education_h_status_75447a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hallticket',
            unique_together={('tenant', 'exam', 'student')},
        ),
    ]
