# Generated by Django 5.2.4 on 2025-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_exam_examschedule_seatingarrangement_hallticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Transfer'), ('CARD', 'Card Payment'), ('UPI', 'UPI'), ('RAZORPAY', 'Razorpay')], default='CASH', max_length=50),
        ),
    ]
