# Generated by Django 5.2.4 on 2026-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 5, 12, 18. 0 means no tax is calculated', max_digits=5),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code printed on GST invoices', max_length=8),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='price_includes_tax',
            field=models.BooleanField(default=True, help_text='Selling price already contains GST (normal for MRP items)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 5, 12, 18. 0 means no tax is calculated', max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code printed on GST invoices', max_length=8),
        ),
    ]
