# Generated by Django 5.2.4 on 2026-09-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_visitorlead'),
        ('restaurant', '0002_order_customer_email_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.JSONField(help_text='List of items with modifiers')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='restaurant.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(help_text='List of ingredients with quantities (e.g., [{"item": "Flour", "qty": 200, "unit": "g"}])')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurant.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.tenant')),
            ],
        ),
    ]
