# Generated by Django 5.2.4 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_kdsticket_recipebom'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 5. 0 means no tax is calculated', max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_includes_tax',
            field=models.BooleanField(default=True, help_text='The listed price already contains GST'),
        ),
        migrations.AddField(
            model_name='order',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
