# Generated by Django 5.2.4 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_housekeepingtask_roomserviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage. 0 means no tax is calculated', max_digits=5),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_includes_tax',
            field=models.BooleanField(default=False, help_text='The listed price already contains GST'),
        ),
    ]
