import os
import json
from openai import OpenAI, AzureOpenAI
from api.models.communications import CommunicationThread, CommunicationMessage
from api.models.tenant_features import TenantFeatureConfig
from api.models.user import Tenant
from api.models.crm import Contact, Deal

PLATFORM_OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "dummy_key_for_builds")


def _track_tokens(config, count):
    if config and count:
        config.ai_tokens_used_this_month += count
        config.save(update_fields=['ai_tokens_used_this_month'])

# Define the tools for RAG and CRM Lead Capture
TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "check_inventory",
            "description": "Check if a specific product or service is available in the business's live inventory or stock.",
            "parameters": {
                "type": "object",
                "properties": {
                    "search_term": {
                        "type": "string",
                        "description": "The name of the product, medicine, or service to search for."
                    }
                },
                "required": ["search_term"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "create_hot_lead",
            "description": "Create a new Deal/Lead in the CRM pipeline if the customer shows strong intent to buy, book, or visit.",
            "parameters": {
                "type": "object",
                "properties": {
                    "customer_name": {
                        "type": "string",
                        "description": "The name of the customer, if known. Default to 'Unknown Customer' if not."
                    },
                    "intent_summary": {
                        "type": "string",
                        "description": "A brief summary of what the customer wants to buy or book."
                    }
                },
                "required": ["customer_name", "intent_summary"]
            }
        }
    }
]

def execute_check_inventory(tenant, search_term):
    """Dynamically checks the correct database based on the Tenant's industry."""
    search_term = search_term.lower()
    
    if tenant.industry == 'pharmacy':
        from pharmacy.models import Medicine
        matches = Medicine.objects.filter(tenant=tenant, name__icontains=search_term)[:3]
        if not matches:
            return f"No stock found for '{search_term}'."
        result = []
        for m in matches:
            # Assuming stock property exists or we just say it's in stock
            result.append(f"{m.name} is available. Price: {m.selling_price if hasattr(m, 'selling_price') else 'Varies'}")
        return "\\n".join(result)
        
    elif tenant.industry == 'salon':
        # Mocking salon service check
        return f"Yes, we offer {search_term}. Please let me know what time you'd like to book!"
        
    return "Inventory check complete. Please inform the customer."

def execute_create_hot_lead(tenant, customer_name, intent_summary):
    """Creates a Lead in the CRM."""
    try:
        # Create a basic contact
        contact, _ = Contact.objects.get_or_create(
            tenant=tenant, 
            first_name=customer_name,
            defaults={'email': f"{customer_name.replace(' ', '').lower()}@example.com"}
        )
        # Create the Deal
        Deal.objects.create(
            tenant=tenant,
            name=f"AI Lead: {intent_summary[:50]}",
            description=f"Auto-generated by AI Omnichannel: {intent_summary}",
            amount=0.00,
            contact=contact,
            stage='lead',
            probability=50
        )
        return "SUCCESS: Lead created in CRM. Sales team will follow up."
    except Exception as e:
        return f"ERROR creating lead: {str(e)}"

def _reply_via_openai_compatible(config, system_prompt, messages_payload, tenant, max_tokens):
    """Full-featured path (tool calling for inventory/lead capture) shared by
    OpenAI and Azure OpenAI, since Azure OpenAI uses the same chat-completions
    interface as the openai package - just a different client/model."""
    if config and config.ai_provider == 'azure_openai' and config.azure_openai_api_key and config.azure_openai_endpoint and config.azure_openai_deployment_name:
        endpoint = config.azure_openai_endpoint.strip()
        if '/v1' in endpoint:
            # Azure's newer unified "v1" API surface (what Foundry's "Use your
            # model in code" snippet now generates by default) is addressed
            # like a plain OpenAI-compatible endpoint - it rejects the
            # api_version query param the classic AzureOpenAI client adds.
            # Foundry's snippet sometimes appends a specific route like
            # "/responses" onto the v1 base (Azure's newer Responses API) -
            # the openai SDK needs the bare ".../v1/" base and appends
            # "/chat/completions" itself, so strip any such suffix back to
            # the v1 root or the request 404s against a nonsense path.
            base_url = endpoint[:endpoint.index('/v1') + len('/v1')] + '/'
            client = OpenAI(api_key=config.azure_openai_api_key, base_url=base_url)
        else:
            # Classic Azure OpenAI endpoint (https://<resource>.openai.azure.com/)
            client = AzureOpenAI(
                api_key=config.azure_openai_api_key,
                azure_endpoint=endpoint,
                api_version="2024-02-01"
            )
        model = config.azure_openai_deployment_name
    else:
        # Plain OpenAI: prefer the tenant's own BYOK key, fall back to the
        # platform key (also used when a non-OpenAI provider was selected
        # but its credentials weren't fully filled in).
        api_key = (config.openai_api_key if config and config.openai_api_key else PLATFORM_OPENAI_API_KEY)
        client = OpenAI(api_key=api_key)
        model = "gpt-4o-mini"

    response = client.chat.completions.create(
        model=model,
        messages=messages_payload,
        max_tokens=max_tokens,
        temperature=0.7,
        tools=TOOLS,
        tool_choice="auto"
    )

    message = response.choices[0].message
    if hasattr(response, 'usage'):
        _track_tokens(config, response.usage.total_tokens)

    if message.tool_calls:
        for tool_call in message.tool_calls:
            function_name = tool_call.function.name
            args = json.loads(tool_call.function.arguments)

            tool_result = ""
            if function_name == "check_inventory":
                tool_result = execute_check_inventory(tenant, args.get("search_term"))
            elif function_name == "create_hot_lead":
                tool_result = execute_create_hot_lead(tenant, args.get("customer_name"), args.get("intent_summary"))

            messages_payload.append(message)
            messages_payload.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": function_name,
                "content": tool_result
            })

        second_response = client.chat.completions.create(
            model=model,
            messages=messages_payload,
            max_tokens=max_tokens,
            temperature=0.7
        )
        if hasattr(second_response, 'usage'):
            _track_tokens(config, second_response.usage.total_tokens)
        return second_response.choices[0].message.content

    return message.content


def _reply_via_gemini(config, system_prompt, history, max_tokens):
    """Plain conversational reply via Google Gemini. No tool-calling support
    yet (inventory check / lead capture) - Gemini's function-calling schema
    differs enough from OpenAI's that it needs its own implementation later."""
    import google.generativeai as genai
    genai.configure(api_key=config.gemini_api_key)
    model = genai.GenerativeModel(
        model_name=config.gemini_model or 'gemini-1.5-flash',
        system_instruction=system_prompt
    )
    contents = [{"role": ("user" if m["role"] == "user" else "model"), "parts": [m["content"]]} for m in history]
    response = model.generate_content(contents, generation_config={"max_output_tokens": max_tokens, "temperature": 0.7})

    if hasattr(response, 'usage_metadata') and response.usage_metadata:
        _track_tokens(config, getattr(response.usage_metadata, 'total_token_count', 0))

    return response.text


def _reply_via_claude(config, system_prompt, history, max_tokens):
    """Plain conversational reply via Anthropic Claude. No tool-calling
    support yet - see _reply_via_gemini for why."""
    import anthropic
    client = anthropic.Anthropic(api_key=config.claude_api_key)
    response = client.messages.create(
        model=config.claude_model or 'claude-3-5-sonnet-latest',
        system=system_prompt,
        messages=[{"role": m["role"], "content": m["content"]} for m in history],
        max_tokens=max_tokens
    )

    if hasattr(response, 'usage') and response.usage:
        _track_tokens(config, (response.usage.input_tokens or 0) + (response.usage.output_tokens or 0))

    return response.content[0].text if response.content else ""


def generate_smart_reply(thread: CommunicationThread, max_tokens: int = 150) -> str:
    tenant = thread.tenant
    config = TenantFeatureConfig.objects.filter(tenant=tenant).first()

    system_prompt = f"You are a helpful, professional assistant for '{tenant.name}'."
    if tenant.industry:
        system_prompt += f" Industry: {tenant.industry}."

    system_prompt += (
        " You have tools to check live inventory and create CRM leads. "
        "1. If a customer asks if you have something in stock, USE the check_inventory tool! Do not guess. "
        "2. If a customer says they want to buy, book, or says 'I am interested', USE the create_hot_lead tool! "
        "Keep answers concise and friendly."
    )

    history = CommunicationMessage.objects.filter(thread=thread).order_by('-created_at')[:10]
    history = list(history)[::-1]
    history_payload = [
        {"role": ("user" if msg.sender_type == 'client' else "assistant"), "content": msg.content}
        for msg in history
    ]

    provider = config.ai_provider if config else 'openai'

    try:
        if provider == 'gemini' and config and config.gemini_api_key:
            return _reply_via_gemini(config, system_prompt, history_payload, max_tokens)
        if provider == 'claude' and config and config.claude_api_key:
            return _reply_via_claude(config, system_prompt, history_payload, max_tokens)

        # openai, azure_openai, or an unconfigured non-OpenAI provider
        # (falls back to OpenAI so replies keep working either way)
        messages_payload = [{"role": "system", "content": system_prompt}] + history_payload
        return _reply_via_openai_compatible(config, system_prompt, messages_payload, tenant, max_tokens)

    except Exception as e:
        print(f"AI provider ({provider}) error: {e}")
        return "I'm sorry, I'm having trouble processing that right now. Please try again later."
