import os
import json
from openai import OpenAI
from api.models.communications import CommunicationThread, CommunicationMessage
from api.models.tenant_features import TenantFeatureConfig
from api.models.user import Tenant
from api.models.crm import Contact, Deal

api_key = os.getenv("OPENAI_API_KEY", "dummy_key_for_builds")
client = OpenAI(api_key=api_key)

# Define the tools for RAG and CRM Lead Capture
TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "check_inventory",
            "description": "Check if a specific product or service is available in the business's live inventory or stock.",
            "parameters": {
                "type": "object",
                "properties": {
                    "search_term": {
                        "type": "string",
                        "description": "The name of the product, medicine, or service to search for."
                    }
                },
                "required": ["search_term"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "create_hot_lead",
            "description": "Create a new Deal/Lead in the CRM pipeline if the customer shows strong intent to buy, book, or visit.",
            "parameters": {
                "type": "object",
                "properties": {
                    "customer_name": {
                        "type": "string",
                        "description": "The name of the customer, if known. Default to 'Unknown Customer' if not."
                    },
                    "intent_summary": {
                        "type": "string",
                        "description": "A brief summary of what the customer wants to buy or book."
                    }
                },
                "required": ["customer_name", "intent_summary"]
            }
        }
    }
]

def execute_check_inventory(tenant, search_term):
    """Dynamically checks the correct database based on the Tenant's industry."""
    search_term = search_term.lower()
    
    if tenant.industry == 'pharmacy':
        from pharmacy.models import Medicine
        matches = Medicine.objects.filter(tenant=tenant, name__icontains=search_term)[:3]
        if not matches:
            return f"No stock found for '{search_term}'."
        result = []
        for m in matches:
            # Assuming stock property exists or we just say it's in stock
            result.append(f"{m.name} is available. Price: {m.selling_price if hasattr(m, 'selling_price') else 'Varies'}")
        return "\\n".join(result)
        
    elif tenant.industry == 'salon':
        # Mocking salon service check
        return f"Yes, we offer {search_term}. Please let me know what time you'd like to book!"
        
    return "Inventory check complete. Please inform the customer."

def execute_create_hot_lead(tenant, customer_name, intent_summary):
    """Creates a Lead in the CRM."""
    try:
        # Create a basic contact
        contact, _ = Contact.objects.get_or_create(
            tenant=tenant, 
            first_name=customer_name,
            defaults={'email': f"{customer_name.replace(' ', '').lower()}@example.com"}
        )
        # Create the Deal
        Deal.objects.create(
            tenant=tenant,
            name=f"AI Lead: {intent_summary[:50]}",
            description=f"Auto-generated by AI Omnichannel: {intent_summary}",
            amount=0.00,
            contact=contact,
            stage='lead',
            probability=50
        )
        return "SUCCESS: Lead created in CRM. Sales team will follow up."
    except Exception as e:
        return f"ERROR creating lead: {str(e)}"

def generate_smart_reply(thread: CommunicationThread, max_tokens: int = 150) -> str:
    tenant = thread.tenant
    
    system_prompt = f"You are a helpful, professional assistant for '{tenant.name}'."
    if tenant.industry:
        system_prompt += f" Industry: {tenant.industry}."
    
    system_prompt += (
        " You have tools to check live inventory and create CRM leads. "
        "1. If a customer asks if you have something in stock, USE the check_inventory tool! Do not guess. "
        "2. If a customer says they want to buy, book, or says 'I am interested', USE the create_hot_lead tool! "
        "Keep answers concise and friendly."
    )
    
    messages_payload = [{"role": "system", "content": system_prompt}]
    
    history = CommunicationMessage.objects.filter(thread=thread).order_by('-created_at')[:10]
    history = list(history)[::-1]
    
    for msg in history:
        role = "user" if msg.sender_type == 'client' else "assistant"
        messages_payload.append({"role": role, "content": msg.content})
        
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages_payload,
            max_tokens=max_tokens,
            temperature=0.7,
            tools=TOOLS,
            tool_choice="auto"
        )
        
        message = response.choices[0].message
        
        # Track Tokens
        config = TenantFeatureConfig.objects.filter(tenant=tenant).first()
        if config and hasattr(response, 'usage'):
            config.ai_tokens_used_this_month += response.usage.total_tokens
            config.save(update_fields=['ai_tokens_used_this_month'])

        # Check if the AI wanted to call a tool
        if message.tool_calls:
            for tool_call in message.tool_calls:
                function_name = tool_call.function.name
                args = json.loads(tool_call.function.arguments)
                
                tool_result = ""
                if function_name == "check_inventory":
                    tool_result = execute_check_inventory(tenant, args.get("search_term"))
                elif function_name == "create_hot_lead":
                    tool_result = execute_create_hot_lead(tenant, args.get("customer_name"), args.get("intent_summary"))
                
                # Append the tool call and result to the messages
                messages_payload.append(message)
                messages_payload.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "name": function_name,
                    "content": tool_result
                })
            
            # Get the final answer from OpenAI after seeing the tool result
            second_response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages_payload,
                max_tokens=max_tokens,
                temperature=0.7
            )
            
            # Track Tokens for second call
            if config and hasattr(second_response, 'usage'):
                config.ai_tokens_used_this_month += second_response.usage.total_tokens
                config.save(update_fields=['ai_tokens_used_this_month'])
                
            return second_response.choices[0].message.content
            
        return message.content
        
    except Exception as e:
        print(f"OpenAI API Error: {e}")
        return "I'm sorry, I'm having trouble processing that right now. Please try again later."
