# Generated by Django 5.2.4 on 2025-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_customer_tenant_alter_goodsreceipt_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='retail/products/'),
        ),
    ]
