# Generated by Django 5.2.4 on 2025-11-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_api_support_tenant__idx_api_support_tenant__c954e0_idx_and_more'),
        ('retail', '0004_add_sale_return_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the price list (e.g., 'Wholesale Price List', 'Distributor Pricing')", max_length=100)),
                ('customer_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('DISTRIBUTOR', 'Distributor'), ('ALL', 'All Types')], default='ALL', help_text='Customer type this price list applies to', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default price list for this customer type')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, help_text='Price list valid from date', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Price list valid until date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_price_lists', to='api.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='Custom price list for this customer (overrides default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='retail.pricelist'),
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this product in this price list', max_digits=10)),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum quantity for this price to apply')),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum quantity for this price (null for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'ordering': ['product__name', 'min_quantity'],
                'unique_together': {('price_list', 'product', 'min_quantity')},
            },
        ),
    ]
