# Generated by Django 5.2.4 on 2025-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_add_quotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit'), ('RAZORPAY', 'Razorpay')], default='CASH', max_length=50),
        ),
    ]
