# Generated by Django 5.2.4 on 2026-09-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_visitorlead'),
        ('retail', '0007_alter_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=100, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='retail.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_barcodes', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received'), ('lost', 'Lost/Damaged')], default='in_transit', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transits', to='api.tenant')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_records', to='retail.stocktransfer')),
            ],
        ),
    ]
